CadastroDeBandas/CadastroDeBandas/Models/Banda.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace CadastroDeBandas.Models
{
    [Table("Banda")]
    public class Banda
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Campo nome é obrigatório")]
        public string Nome { get; set; }
        [DisplayName("Ano de formação")]
        [Required(ErrorMessage = "Campo Ano de formação é obrigatório")]
        public int AnoFormacao { get; set; }
        //[DataType(DataType.MultilineText)]
        public string Estilo { get; set; }
        [DisplayName("País")]
        public string Pais { get; set; }
        [DisplayName("Classificação")]
        [Required(ErrorMessage = "Campo classificação é obrigatório")]
        [Range(0,5,ErrorMessage="A classificação deve ser de 0 a 5")]
        [ValidaPar(ErrorMessage="A classificação deve ser par")]
        public int Classificacao { get; set; }

        [StringLength(100)]
        public string  Twitter { get; set; }

        public virtual ICollection<Musica> Musicas { get; set; }
        public virtual ICollection<Musico> Integrantes { get; set; }

        public IEnumerable<Banda> ListarBandas()
        {
            yield return new Banda { Id = 1, Nome = "Iron Maiden", AnoFormacao = 1980, Classificacao = 5, Estilo = "Rock", Pais = "Inglaterra" };
            yield return new Banda { Id = 2, Nome = "Dream Theater", AnoFormacao = 1988, Classificacao = 5, Estilo = "Rock", Pais = "EUA" };
        }
    }
}

CadastroDeBandas/CadastroDeBandas/Controllers/BandaController.cs
using CadastroDeBandas.ActionFilters;
using CadastroDeBandas.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CadastroDeBandas.Controllers
{
    public class BandaController : Controller
    {
        public PartialViewResult PartialMusicas(int id) {
            var musicas = new Repositorio().ListarMusicas(id);
            return PartialView( musicas);
        }

        public ActionResult ExemploHelpers() {
            return View(new Banda { Pais="Brasil"});
        }

        public string ActionTeste() {
            return "Esta é uma mensagem bla bla bla bla bla";
        }

        public ActionResult Index()
        {
            var bandas = new Repositorio().ListarBandas();
            return View(bandas);
        }


        [LoggerFilter]
        public ActionResult Details(int id)
        {
            var banda = new Repositorio().BuscarBanda(id);
            return View(banda);
        }
        //[Authorize]
        //[OutputCache(Duration=60)]
        public ActionResult Details2(string pais,string cor)
        {
            System.Threading.Thread.Sleep(10000);

            var banda = new Repositorio().BuscarBandaPorPais(pais).FirstOrDefault();

            ViewBag.texto = "Você escolheu a cor " + cor + " para a banda " + banda.Nome;
            ViewBag.color = cor;
            return View("Details",banda);
        }
        //
        // GET: /Banda/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Banda/Create

        [HttpPost]
        public ActionResult Create(Banda banda)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    new Repositorio().IncluirBanda(banda);
                    return RedirectToAction("Index");
                }

                return View("ExemploHelpers");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Banda/Edit/5

        public ActionResult Edit(int id)
        {
            var banda = new Repositorio().BuscarBanda(id);
            return View(banda);
        }

        //
        // POST: /Banda/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, Banda banda)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    new Repositorio().AlterarBanda(banda);
                    return RedirectToAction("Index");
                }

                return View();
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Banda/Delete/5

        public ActionResult Delete(int id)
        {
            var banda = new Repositorio().BuscarBanda(id);
            return View(banda);
        }

        //
        // POST: /Banda/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                new Repositorio().ExcluirBanda(id);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

CadastroDeBandas/CadastroDeBandas/Controllers/MusicaController.cs
using CadastroDeBandas.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CadastroDeBandas.Controllers
{
    public class MusicaController : Controller
    {
        //
        // GET: /Musica/

        public ActionResult Index(int id)
        {
            var repositorio = new Repositorio();
            var musicas = repositorio.ListarMusicas(id);
            return View(musicas);
        }

        //
        // GET: /Musica/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Musica/Create

        public ActionResult Create(int id)
        {
            var musica = new Musica { BandaId = id };
            return View(musica);
        }

        //
        // POST: /Musica/Create

        [HttpPost]
        public ActionResult Create(Musica musica)
        {
            try
            {
                new Repositorio().IncluirMusica(musica);

                return RedirectToAction("Index","Banda");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Musica/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Musica/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Musica/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Musica/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

CadastroDeBandas/CadastroDeBandas/Views/Banda/Create.cshtml
@model CadastroDeBandas.Models.Banda

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Banda</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Nome)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Nome)
            @Html.ValidationMessageFor(model => model.Nome)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.AnoFormacao)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AnoFormacao)
            @Html.ValidationMessageFor(model => model.AnoFormacao)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Estilo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Estilo)
            @Html.ValidationMessageFor(model => model.Estilo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Pais)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Pais)
            @Html.ValidationMessageFor(model => model.Pais)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Classificacao)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Classificacao)
            @Html.ValidationMessageFor(model => model.Classificacao)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CadastroDeBandas/CadastroDeBandas/Views/Banda/Delete.cshtml
@model CadastroDeBandas.Models.Banda

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Banda</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Nome)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Nome)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.AnoFormacao)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.AnoFormacao)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Estilo)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Estilo)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Pais)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Pais)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Classificacao)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Classificacao)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Twitter)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Twitter)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

CadastroDeBandas/CadastroDeBandas/Views/Banda/Details.cshtml
@model CadastroDeBandas.Models.Banda

@{
    ViewBag.Title = "Details";
}

<h1 style="color:@ViewBag.color">@ViewBag.texto</h1>

<h2>Details</h2>

<fieldset>
    <legend>Banda</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Nome)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Nome)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.AnoFormacao)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.AnoFormacao)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Estilo)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Estilo)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Pais)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Pais)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Classificacao)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Classificacao)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Twitter)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Twitter)
    </div>
</fieldset>
@Html.Action("PartialMusicas",new {id=Model.Id})



<p>
     @Html.ActionLink("Cadastrar nova música", "Create", "Musica", new {id=Model.Id },null)
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

@Model.Nome
<br />
@Model.Pais
<br />
<marquee>@Model.Twitter</marquee>

CadastroDeBandas/CadastroDeBandas/Views/Banda/Edit.cshtml
@model CadastroDeBandas.Models.Banda

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Banda</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Nome)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Nome)
            @Html.ValidationMessageFor(model => model.Nome)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.AnoFormacao)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AnoFormacao)
            @Html.ValidationMessageFor(model => model.AnoFormacao)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Estilo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Estilo)
            @Html.ValidationMessageFor(model => model.Estilo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Pais)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Pais)
            @Html.ValidationMessageFor(model => model.Pais)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Classificacao)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Classificacao)
            @Html.ValidationMessageFor(model => model.Classificacao)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Twitter)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Twitter)
            @Html.ValidationMessageFor(model => model.Twitter)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CadastroDeBandas/CadastroDeBandas/Views/Banda/ExemploHelpers.cshtml
@model CadastroDeBandas.Models.Banda

@{
    ViewBag.Title = "ExemploHelpers";
}

<h2>ExemploHelpers</h2>

<h3>Action link / Action</h3>
@Html.ActionLink("Clique aqui", "Index", "Home")
<p>@Html.Action("ActionTeste")</p>

<h3>Display</h3>
@Html.DisplayNameFor(x => x.Pais)<br />
@Html.DisplayFor(x => x.Pais)

<h3>Begin form</h3>
@using (Html.BeginForm("Create", "Banda", FormMethod.Post))
{
    @Html.ValidationSummary(false)

    @Html.LabelFor(x => x.Nome)
    @Html.EditorFor(x => x.Nome)
    @Html.ValidationMessageFor(x => x.Nome)

    <br />
    @Html.LabelFor(x => x.Pais)
    @Html.TextBoxFor(x => x.Pais, new { placeholder = "Digite o país", style = "color:red", @class = "textoblablabla" })
    
    <input type="submit" name="btn" value="Enviar" />
}

CadastroDeBandas/CadastroDeBandas/Views/Banda/Index.cshtml
@model IEnumerable<CadastroDeBandas.Models.Banda>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AnoFormacao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estilo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pais)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Classificacao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Twitter)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AnoFormacao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estilo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pais)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Classificacao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Twitter)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>

<label for="bandas">Escolha a banda</label>
<select id="bandas">
    <option value="0">-----------</option>
    @foreach (var item in Model)
    {
        <option id="@item.Id">@item.Nome</option>
    }
</select>

<hr />
<ul>
    @foreach (var item in Model.Where(x=>x.Classificacao>2))
    {
        <li>@item.Nome</li>
    }
</ul>

@{
    var nomes = new string[] { "Paulo", "Thales", "Agnes" };
    <ol>
        @foreach (var item in nomes)
        {
            <li>@item</li>  
        }

    </ol> 
}

<h1>@Model.First().Nome</h1>